version: '3.3'
services:
  mysqlService:
    image: mysql:5.5
    ports:
      - 3306:3306
    container_name: mysql-container
    network_mode: host
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  userService:
    image: userimage
    build: MongoDb Crud/
    hostname: localhost
    restart: always
    network_mode: host
    depends_on:
      - mongo
      - eurekaserver
      - cloudapiservice
    ports:
      - 8086:8086
  mongo:
    image: mongo:3.2-jessie
    ports:
        - 27017:27017
    container_name: mongo
    network_mode: host

  securityservice:
    container_name: security-service
    build: SpringJWTSecurity/
    hostname: localhost
    network_mode: host
    ports:
      - 8085:8085
    depends_on:
      - mysqlService
      - eurekaserver
      - cloudapiservice
    restart: always

  cloudapiservice:
    image: cloud-api-service
    build: APIGatewayService/APIGatewayService
    restart: always
    network_mode: host
    ports:
      - 9000:9000
    environment:
      API_GATEWAY_PORT: 9000
      EUREKA_SERVER_IP: localhost
      EUREKA_SERVER_PORT: 8761
    depends_on:
      - eurekaserver

  eurekaserver:
      image: eureka-server
      build: EurekaServer/
      restart: always
      network_mode: host
      environment:
        Eureka_server_port: 8761
      ports:
          - 8761:8761
