FROM openjdk
WORKDIR usr/lib
EXPOSE 8085
ADD ./target/SpringJWTSecurity-0.0.1-SNAPSHOT.jar /usr/lib/SpringJWTSecurity-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","SpringJWTSecurity-0.0.1-SNAPSHOT.jar"]